### ISSUE TITLE
Research paper PDF

### ISSUE THREAD

**Issue by aleemb** [jreades/urb-studies-predicting-gentrification#1]
Could you please share the research paper? A link or email aleemb (@) gmail. Would be interested to read through it.

**Comment by grandchild** [comment]
* wikipedia: sci-hub
* take one of the links from the right
* prepend sci-hub URL to the doi given in the description
-> go to `"www.sci-hub." + $SCIHUB_TLD_DU_JOUR + "/10.1177/0042098018789054"` and there you are :grin:

**Comment by jreades** [comment]
Yes, you can do that. There's also an author version on our Institutional Repository linked to from the README if you aren't comfortable/familiar with SciHub.
