### ISSUE TITLE
pysal version

### ISSUE THREAD

**Issue by feliuserra** [jreades/urb-studies-predicting-gentrification#2]
Hi,

Thanks for sharing this great work. I have been trying to reproduce your code and it seems that the pysal version that you were using is outdated. The first notebook that it crashes on is on the notebook ```02-Scoring Data Download and Prep.ipynb``` with the following error:

```
AttributeError: module 'pysal' has no attribute 'queen_from_shapefile'
```

By googling a bit I have found that this method is available on the version 1.11 of pysal. After downgrading it, it seems that there are other methods that were not available back then and it crashes.

Could you please specify the pysal version that you were using for this?

Thanks in advance,

Feliu

**Comment by jreades** [comment]
I've updated the repository to include an environment.yml file which is a full 'dump' of my Anaconda repository, including all versioning information: in this case I was using PySAL 1.14 and PySAL 2.x represents a major change that I've not had time to address. The README has been updated accordingly so hopefully this is enough to get you up and running.

**Comment by feliuserra** [comment]
Hi,

Thanks for your quick answer. I have tried to create a new environment with the new ```environment.yml``` that you uploaded but then the new environment is failing to be resolved. In concrete, the error I get is:

```
Solving environment: failed

ResolvePackageNotFound:
  - libgdal==2.2.4=4
  - libxml2==2.9.8=0
  - libiconv==1.15=0
  - libtiff==4.0.9=0
```

I wanted to try removing these and install them with pip install after removing them from the ```.yml```, but then after I remove them and try to run ```conda-env create -f environment.yml```, I get this error:

```
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - gdal==2.2.4=py36_0
  - jpeg==9b=2
  - json-c==0.12.1=0
```
I am running this on a MacOS Mojave version 10.14, with the python version that you specified. I don't know what else could I try out, perhaps I should create a VM and try this .yml on ubuntu? I don't know. Thanks again for your time and patience.

Best,

F.

**Comment by jreades** [comment]
Hmmm, I'm still running High Sierra at the moment (since I _know_ that major upgrades always break something and don't have the time to debug right now) and I wonder if there aren't (yet) conda packages for Mojave and something is broken therein? That said, I've checked all of the packages that you listed and they all seem to have been installed from conda-forge --- can you try something like I'm doing this quickly from memory, so I may have the syntax wrong):
```
conda install -c conda-forge gdal=2.2.4 jpeg=9b json=0.12.1
``` 
That's just forcing conda to look in the conda-forge channel instead of the 'default' one... though the setup.yml and environment.yml files should have forced that I'd have thought.

Are there any other errors in the history for your installation?

jon

**Comment by feliuserra** [comment]
Hi, 

I still cannot get this done. I don't know if you updated the requirements with this command but could you please freeze the environment that you are using into a file with the following command:

```conda list --explicit```

There doesn't seem to be any other errors that I can provide for further details. Could you try to create a new fresh environment setting ```PYTHONUSERSITE=1```. (see this link https://github.com/conda/conda/issues/6018 for further explanations). 

Thanks in advance,

**Comment by jreades** [comment]
I've attached the dump from `conda list` in the hopes that that will help. It's hard to tell from a _quick_ scan of the explicit output whether I am getting pollution from other environments of the mlgent environment. Just to check my reading of the other link, is it the case that I need to add:

```
export PYTHONNOUSERSITE=True
```

to my `.bashrc` file, or is this something that goes into a YAML script (the syntax looks bash/environment-like)?

jon
[conda_list_--explicit.txt](https://github.com/jreades/urb-studies-predicting-gentrification/files/2884948/conda_list_--explicit.txt)

**Comment by feliuserra** [comment]
Hi Jon,

Thanks for the quick answer. You just need to execute the command before you activate the conda environment, I don't think you need to add it to the ```.bashrc```, although you can. It'll be set to show only the ones in the environment you are using. This is to avoid package leakeages from your conda base environment.

For now I am just going package by package, looking at your explicit list trying to set manually the packages that you specified.

Did you do the PYTHONNOUSERSITE before the creating explicit? You can check it by running:

```
import sys

print(sys.path)
```
and check whether there is some package leakage.

I don't know what else could I try, I am stuck, if you have any other suggestion or idea I'd appreciate it.

Thank you very much

**Comment by feliuserra** [comment]
Hi,

I am still stuck in this.  The "solving environment step" from conda keeps failing. I have tried several times to setup a new environment.yml and try to solve the dependencies manually but new errors keep showing up and I can't manage to solve it (plus it's never a good idea to do this). I've also tried to use ```pipenv -c .``` but it also doesn't work. Anything else I could try? Thanks

**Comment by jreades** [comment]
Hi -- I've not had time to dig into this but am trying to do so now by setting up a clean environment and restarting my own install from scratch to see what's what. 

I've also now had a chance to re-run the environment dump. Output of sys.path is:
```python
['', '/anaconda3/envs/mlgent/lib/python36.zip', '/anaconda3/envs/mlgent/lib/python3.6', '/anaconda3/envs/mlgent/lib/python3.6/lib-dynload', '/anaconda3/envs/mlgent/lib/python3.6/site-packages', '/anaconda3/envs/mlgent/lib/python3.6/site-packages/cycler-0.10.0-py3.6.egg']
```
Output of `explicit` is attached.

Jon
[conda_list_--explicit.txt](https://github.com/jreades/urb-studies-predicting-gentrification/files/2957125/conda_list_--explicit.txt)

**Comment by jreades** [comment]
To set up the clean env I'm going to actually create completely new v-env with the user site set to true and fixing some of the key libs to the versions that I need (I'll try with as few as possible to begin with).

**Comment by jreades** [comment]
I've made some pretty substantial changes to setup.yml and have updated to Python 3.7. On my Mac this seems to enable me to install a complete environment from scratch without errors (except a note about clobbering a jupyter lib). I need to clone and re-run the entire thing from scratch to be sure this works though. I can, however, at least run the first two notebooks with no errors and no warnings.

**Comment by jreades** [comment]
I've now tested this on a brand new environment and had no issues. Can you please checkout either the HEAD or tag v1.1 and let me know if it works for you? Thanks! I've provisionally closed it but happy to reopen if you're still having issues.

**Comment by feliuserra** [comment]
Hi, sorry for the late reply, that is so great. Thank you so much for this! Everything works smoothly, just had to follow the instructions from the new setup.yml.

Cheers
