### ISSUE TITLE
Missing shapefile?

### ISSUE THREAD

**Issue by StevenKema** [jreades/urb-studies-predicting-gentrification#3]
Hey, I'm trying to replicate your research but I'm running into some issues. 
In Notebook 2 (Scoring Data Download and Preparation) you use the file `Lower_Layer_Super_Output_Areas_December_2011_Generalised_Clipped__Boundaries_in_England_and_Wales.shp`, but I don't think this file is downloaded in the first Notebook. After googling I found this [shapefile](http://geoportal.statistics.gov.uk/datasets/da831f80764346889837c72508f046fa_3). Is this the same file? Using it gives me a warning: 
```
pysal/weights/weights.py:186: UserWarning: There is one disconnected observation (no neighbors)
  warnings.warn("There is one disconnected observation (no neighbors)")
 UserWarning: Island id: 18535
  warnings.warn("Island id: %s" % str(self.islands[0]))
```
Running the code block after it (the get_neighbours and get_gmean_from_neighbours part) I get the following error:
```
2001...
	Looking for neighbours of 27 areas without house prices.
['E01033573' 'E01000552' 'E01000599' 'E01033424' 'E01033734' 'E01033735'
 'E01033739' 'E01032789' 'E01002089' 'E01033030' 'E01033487' 'E01033493'
 'E01002904' 'E01002907' 'E01003184' 'E01003244' 'E01033574' 'E01033575'
 'E01033578' 'E01003971' 'E01004011' 'E01004268' 'E01032771' 'E01032773'
 'E01032779' 'E01033098' 'E01033593']
Finding neighbours for E01033573
	Searching for: E01032569, E01033084, E01033098, E01032576, E01033572, E01033575
	Found median prices: 178000.0, 119975.0, 165000.0, 111000.0, nan, nan
	E01033573 has been assigned geometric mean of neighbours: 140630.0
Finding neighbours for E01000552
	Searching for: E01004708, E01004710, E01000544, E01000550, E01000551
	Found median prices: 210000.0, 156000.0, 150250.0, 227500.0, 220000.0
	E01000552 has been assigned geometric mean of neighbours: 189810.0
Finding neighbours for E01000599

---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
<ipython-input-10-08ff6af9e51e> in <module>()
      5 for z in nan01:
      6     print("Finding neighbours for " + z)
----> 7     neighbours01 = get_neighbours(qw[ cds.index(z) ], fh)
      8     m = get_gmean_from_neighbours(neighbours01, hhv2001)
      9     print("\t" + z + " has been assigned geometric mean of neighbours: " + str(m))

<ipython-input-6-b86406fa08f9> in get_neighbours(ns, col)
     21     for n in ns.keys():
     22         #print(str(n) + " -> " + col[n][0][0])
---> 23         neighbours.append(col[n][0][0]) # Not elegant, but column name changes with year
     24     return neighbours
     25 

/home/steven/anaconda3/lib/python3.6/site-packages/pysal/core/Tables.py in __getitem__(self, key)
    185         else:
    186             self.seek(slice(rows).indices(len(self))[1])
--> 187             data = [next(self)]
    188         if cols is not None:
    189             if isinstance(cols, slice):

/home/steven/anaconda3/lib/python3.6/site-packages/pysal/core/FileIO.py in __next__(self)
    249         """A FileIO object is its own iterator, see StringIO"""
    250         self._complain_ifclosed(self.closed)
--> 251         r = self.__read()
    252         if r is None:
    253             raise StopIteration

/home/steven/anaconda3/lib/python3.6/site-packages/pysal/core/FileIO.py in __read(self)
    312         row = self._read()
    313         if row is None:
--> 314             raise StopIteration
    315         row = self._cast(row)
    316         return row

StopIteration: 
```

**Comment by jreades** [comment]
Yes, that's the right Shapefile -- I thought I'd either included it in the repo or added it as a download. Will need to track that down in the first notebook file and correct!

The other error would appear to be triggered by that LSOA not having any neighbours, but that is a very strange error since they should also have at least some neighbours even if those neighbours have no property transactions and the for loop that's wrapped in should have dealt with those cases anyway.

Obviously, it looks like the two errors might be inter-connected. I'll have to dig through my commit history and see if I did something to/with E01000599 that dealt with this but somehow forgot to include that in the published version.

I'll need to investigate, sorry!

**Comment by jreades** [comment]
Right -- this is now explicitly downloaded in notebook 1 and I've added a test to ensure that it is able to correctly calculate the neighbour weights matrix used in Notebook 2. I need to test this on a brand new instance to be sure everything is correct thought.

**Comment by jreades** [comment]
I've now tested this on a brand new environment and had no issues. Can you please checkout either the HEAD or tag v1.1 and let me know if it works for you? Thanks!
